### ISSUE TITLE
Unable to access admin

### ISSUE THREAD

**Issue by oleiade** [alexellis/ghost-on-docker#9]
Hi,

I've followed the steps described in your blog post. The ghost site is running, and accessible at `http://localhost:2368`. However trying to access the admin page at `http://localhost:2368/ghost` raises the following error:

```
Error: No default engine was specified and no extension was provided.
    at new View (/var/www/ghost/versions/1.4.0/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/var/www/ghost/versions/1.4.0/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/var/www/ghost/versions/1.4.0/node_modules/express/lib/response.js:971:7)
    at HTMLErrorRender (/var/www/ghost/versions/1.4.0/core/server/middleware/error-handler.js:86:9)
    at Layer.handle_error (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at prepareError (/var/www/ghost/versions/1.4.0/core/server/middleware/error-handler.js:58:5)
    at Layer.handle_error (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/1.4.0/node_modules/express/lib/response.js:424:7
    at SendStream.onerror (/var/www/ghost/versions/1.4.0/node_modules/express/lib/response.js:1003:5)
```

Any leads on how to solve this? :-)
Thanks!

**Comment by alexellis** [comment]
Several people have reported success with the image - did you build from scratch or pull mine in? Maybe delete the image you build and pull mine from the hub. I guess the Ghost team have broken their code.

**Comment by oleiade** [comment]
Thanks for your quick answer, I've built it from your repo master branch :-)
I didn't realize it was available on the Hub, I'll trying pulling it from there and will update this issue accordingly.

Cheers

**Comment by alexellis** [comment]
It wasn't available on the Hub when Ghost was released, I've since switched my Dockerfile to point there. Closing the issue for now.
